- name: Ensure that httpd is installed
  yum:
    name: httpd
    state: present
- name: Ensure that httpd is enabled and started
  systemd:
    name: httpd
    state: started
    enabled: yes
- name: configure firewalld for httpd
  firewalld:
    service: http
    permanent: yes
    state: enabled

- name: configure firewalld for ssh
  firewalld:
    service: ssh
    permanent: yes
    state: enabled

- name: enable firewalld
  systemd:
    name: firewalld
    state: started
    enabled: yes

- name: Ensure /var/www/html is exists
  file:
    name: /var/www/html/
    state: directory


- name: Ensure /var/www/html/index.html is exists
  file:
    name: /var/www/html/index.html
    state: touch

- name: Ensure correct innerds of index.html
  lineinfile:
    path: /var/www/html/index.html
    line: "<p> Welcome to my web server </p>"
    state: present
