---
# defaults file for vsftpd
ftp_pub_dir: '/var/ftp/pub'
ftp_upload_dir: '/var/ftp/pub/upload'
anon_en: 'YES'
local_en: 'NO'
anon_root: '/var/ftp/pub'
no_anon_password: 'YES'
anon_upd: 'YES'
anon_mkdir: 'YES'
allow_ftpd_anon_write: 'YES'
listen: 'YES'
listen6: 'NO'

