- name: Ensure that vsftpd is installed same 4 policycoreutils-python-utils for selinux control
  yum:
    name: 
      - vsftpd
      - policycoreutils-python-utils 
    state: present

- name: Ensure that vsftpd is enabled and started
  systemd:
    name: vsftpd
    state: started
    enabled: yes

- name: configure firewalld for ftp
  firewalld:
    port: 21
    permanent: yes
    state: enabled

- name: configure firewalld for ssh
  firewalld:
    service: ssh
    permanent: yes
    state: enabled

- name: enable firewalld
  systemd:
    name: firewalld
    state: started
    enabled: yes
- name: prepare dirs
  file:
    name: "{{ item }}"
    state: directory
  with_items: ["{{ ftp_pub_dir }}", "{{ ftp_upload_dir }}"]

- name: gen conf file
  template:
    src: templates/vsftpd.conf
    dest: /etc/vsftpd/vsftpd.conf
    owner: root
    group: root
    mode: 0740
- name: restart vsftpd for apply settings
  systemd:
   name: vsftpd
   state: restarted

- name: configure selinux
  seboolean:
    name: ftpd_anon_write
    state: yes
    persistent: yes


 
    
    