- name: prepare host for awx installation
  hosts: master
  become: yes
  tasks:
  - name: disable firewalld
    service:
      name: firewalld
      state: stopped
      enabled: false
  - name: disable selinux
    selinux:
      state: disabled
  - name: dnf update
    dnf:
      name: "*"
      state: "latest"
  - name: Install K3s
    shell: curl -sfL https://get.k3s.io | sudo bash - && chmod 644 /etc/rancher/k3s/k3s.yaml
  - name: install needed packs
    dnf:
      name:
        - make
        - git
      state: latest
  - name: clone awx repo
    git:
      repo: https://github.com/ansible/awx-operator.git 
      dest: ~/awx
  - name: configure firewalld for ssh
    firewalld:
      service: ssh
      permanent: yes
      state: enabled
  - name: enable firewalld
    systemd:
      name: firewalld
      state: started
      enabled: yes