all:
  children:
    master:
      hosts:
        control.example.com
    slave:
      hosts:
        node1.example.com
        node1.example.com
    vars:
      ansible_connection = ssh
      ansible_user = vagrant
      ansible_ssh_pass = vagrant
      