- name: Task 1, httpd installation enabling and creating of index.html
  hosts: slave
  become: yes
  tasks:
    - name: Ensure that httpd is installed
      yum:
        name: httpd
        state: present
    - name: Ensure that httpd is enabled and started
      systemd:
        name: httpd
        state: started
        enabled: yes
    - name: configure firewalld
      firewalld:
        service: http
        permanent: yes
        state: enabled
    - name: Ensure /var/www/html is exists
      file:
        name: var/www/html/
        state: directory
  

    - name: Ensure /var/www/html/index.html is exists
      file:
        name: var/www/html/index.html
        state: touch    

    - name: Ensure correct innerds of index.html
      lineinfile:
        path: /var/www/html/index.html
        line: "<p> Welcome to my web server </p>"
        state: present


        
